drop table if exists ss_platform;
drop table if exists ss_default_platform;
drop table if exists ss_version;
drop table if exists ss_default_version;
drop table if exists ss_user;
drop table if exists ss_group;
drop table if exists ss_scenario;
drop table if exists ss_benchmark;
drop table if exists ss_performance;
drop table if exists ss_default_theme;

create table ss_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);

create table ss_platform (
	id bigint generated by default as identity,
	name varchar(20) not null,
	status varchar(10) not null,
	primary key (id)
);

create table ss_default_platform(
    id bigint generated by default as identity,
    platform_id bigint,
 	primary key (id)   
);

create table ss_version (
	id bigint generated by default as identity,
	name varchar(20) not null,
	status varchar(10) not null,
	primary key (id)
);

create table ss_default_version(
    id bigint generated by default as identity,
    version_id bigint,
 	primary key (id)   
);

create table ss_default_theme(
    id bigint generated by default as identity,
	theme varchar(20) not null,
 	primary key (id)   
);

create table ss_group(
    id bigint generated by default as identity,
    name varchar(50) not null,
    description varchar(255),
    position smallint,
    primary key (id)
);

create table ss_scenario (
	id bigint generated by default as identity,
	name varchar(64) not null,
    description varchar(255),
    group_id bigint,
	primary key (id)
);

create table ss_benchmark (
	id bigint generated by default as identity,
	scenario_id bigint,
	platform_id bigint,
    version_id bigint,
	result int NOT NULL,
	primary key (id)
);

create table ss_performance (
	id bigint generated by default as identity,
	scenario_id bigint,
	platform_id bigint,
	version_id bigint,
	result int NOT NULL,
	created TIMESTAMP,
	jenkins varchar(255),
	primary key (id)
);


